### ISSUE TITLE
Error occurred when executing AnyNode:  Expected metadata ...

### ISSUE THREAD

**Issue by WeirdScienceX** [lks-ai/anynode#15]
I tried several of the sample workflows.  Using GPT 3/4 and all result in the same error:

GPT 3.5:

Finding Nodes in Workspace. kwargs: {'id': '4'}
Collection function_registry is not created.
{'prompt': 'output a list of all prime numbers up to the input number', 'function': "An error occurred: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", 'imports': '', 'comment': None, 'input_types': "Type: <class 'int'>\nType: <class 'NoneType'>", 'version': '0.1.2'}
!!! Exception during processing!!! Expected metadata value to be a str, int, float or bool, got None which is a NoneType

GPT 4 (not 4o)

Finding Nodes in Workspace. kwargs: {'id': '4'}
Collection function_registry is not created.
{'prompt': 'output a list of all prime numbers up to the input number', 'function': "An error occurred: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", 'imports': '', 'comment': None, 'input_types': "Type: <class 'int'>\nType: <class 'NoneType'>", 'version': '0.1.2'}
!!! Exception during processing!!! Expected metadata value to be a str, int, float or bool, got None which is a NoneType

**Comment by lks-ai** [comment]
fixed in latest.
