### ISSUE TITLE
any node creates no more link to local LLM

### ISSUE THREAD

**Issue by Presswurscht** [lks-ai/anynode#17]
The request for the local LLM support creates no link to the local ollama server providing a llama3 session. Seems it is hard linked to "gpt-4o"  (set as default in line 124 and 148. I tried to solve it by chaning this to llama3 but that  didn't help.
Can you provide the old version of any.py again ?

**Comment by Presswurscht** [comment]
Error message is: Finding Nodes in Workspace. kwargs: {'id': '2'}
{'prompt': 'Take the input and multiply by 5', 'function': 'An error occurred: API request failed with status code 404: {"error":{"message":"model \'gpt-4o\' not found, try pulling it first","type":"api_error","param":null,"code":null}}', 'imports': '', 'comment': None, 'input_types': "Type: <class 'int'>\nType: <class 'NoneType'>", 'version': '0.1.2'}
!!! Exception during processing!!! Expected metadata value to be a str, int, float or bool, got None which is a NoneType

**Comment by Presswurscht** [comment]
Finding Nodes in Workspace. kwargs: {'id': '2'}
{'prompt': 'Take the input and multiply by 5', 'function': 'An error occurred: API request failed with status code 404: {"error":{"message":"model \'gpt-4o\' not found, try pulling it first","type":"api_error","param":null,"code":null}}', 'imports': '', 'comment': None, 'input_types': "Type: <class 'int'>\nType: <class 'NoneType'>", 'version': '0.1.2'}
!!! Exception during processing!!! Expected metadata value to be a str, int, float or bool, got None which is a NoneType

**Comment by yotraxxx** [comment]
Your issue looks related to mine (thanks for for the clue found on your second message) :
https://github.com/lks-ai/anynode/issues/16#issue-2333878240

**Comment by lks-ai** [comment]
Fixed.
