### ISSUE TITLE
torchaudio issues

### ISSUE THREAD

**Issue by yeslamer** [lks-ai/anynode#22]
File "C:\Users\joelu\Downloads\ComfyUI-Zluda\custom_nodes\anynode\nodes\any.py", line 16, in <module>
    import os, json, random, string, sys, math, datetime, collections, itertools, functools, urllib, shutil, re, torch, time, decimal, matplotlib, io, base64, wave, chromadb, uuid, scipy, torchaudio, torchvision, cv2, PIL
ModuleNotFoundError: No module named 'torchaudio'

how do i fix this? thank you in advance

**Comment by lks-ai** [comment]
I made sure 100% to add torchaudio and torchvision to requirements.txt, thanks! I missed those because I assumed they were already included in comfy requirements. Next time I will verify. I just pushed.
