### ISSUE TITLE
The following error occurred

### ISSUE THREAD

**Issue by lanse6899** [lks-ai/anynode#4]
![微信截图_20240529121756](https://github.com/lks-ai/anynode/assets/167429044/f4a6400e-2931-4f80-973b-977828fb9b73)
![微信截图_20240529121857](https://github.com/lks-ai/anynode/assets/167429044/783ef1a2-2082-4c85-8dcc-4139c826926e)

**Comment by lks-ai** [comment]
I will fix this for next push

**Comment by lks-ai** [comment]
Fixed in latest update
