### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by xavido** [lks-ai/anynode#7]
![image](https://github.com/lks-ai/anynode/assets/31993919/26580385-479f-4e76-a188-96739fdc407c)

Has anyone else had this error when installing the node? I updated, reinstalled, installed via command line and there is no way... always the same error... any ideas or advice?

Thanks!

Xavi

**Comment by xavido** [comment]
Hey! I fixed it. Use scikit-learn at the requirements.txt as sklearn is deprecated.

Thanks!

Xavi

**Comment by generello** [comment]
Wait, i tried editing the requirements.txt removing sklearn and adding scikit-learn... It didn't work. Am I doing something wrong?
